// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:yakmukja/models/medicine.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DoseTimeAdapter());
    registerAdapter(MedicineAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DoseTimeAdapter());
    registerAdapter(MedicineAdapter());
  }
}
